// Calibrates the vehicle classes against real qualifying laps.
//   node scripts/calibrate.ts            report the current model's error per reference lap
//   node scripts/calibrate.ts --fit      also fit grip (and aero level with 3+ references) per class
//   node scripts/calibrate.ts --write    fit and write the result to data/vehicles.json and docs/CALIBRATION.md
import { readFileSync, writeFileSync } from 'node:fs';
import { type CalibrationRow, evaluate, fitClass, formatLapTime, rmsError } from '../src/core/calibration.ts';
import { LINE_MARGIN } from '../src/core/racingLine.ts';
import { VEHICLES, type VehicleFile } from '../src/core/vehicles.ts';
import { DATA_DIR, loadCircuits, loadReferenceLaps } from './circuitData.ts';

const args = new Set(process.argv.slice(2));
const write = args.has('--write');
const fit = write || args.has('--fit');

const refs = loadReferenceLaps();
const circuits = loadCircuits(new Set(refs.map((r) => r.circuit)));

const pct = (e: number) => `${e >= 0 ? '+' : ''}${(e * 100).toFixed(1)}%`;
const rms = (e: number) => `${(e * 100).toFixed(1)}%`;
const file = JSON.parse(readFileSync(`${DATA_DIR}vehicles.json`, 'utf8')) as VehicleFile;
const summary: { id: string; name: string; before: number; after: number; rows: CalibrationRow[] }[] = [];

for (const car of VEHICLES) {
  const result = fit ? fitClass(car, circuits, refs) : null;
  const shown = result ? result.after : evaluate(car, circuits, refs);
  if (!shown.length) continue;
  const before = result ? rmsError(result.before) : rmsError(shown);
  const after = rmsError(shown);
  summary.push({ id: car.id, name: car.name, before, after, rows: shown });
  console.log(`\n${car.name} (${car.spec})${result ? `  grip x${result.gripScale.toFixed(3)}, downforce x${result.downforceScale.toFixed(3)}, load sensitivity ${result.loadSensitivity.toFixed(3)}` : ''}`);
  for (const r of shown) {
    console.log(`  ${r.ref.circuit.padEnd(13)} real ${formatLapTime(r.ref.time).padStart(9)}  model ${formatLapTime(r.simulated).padStart(9)}  ${pct(r.error).padStart(7)}${r.ref.fit ? '' : '  (not fitted)'}`);
  }
  console.log(`  RMS error ${rms(before)}${result ? ` -> ${rms(after)}` : ''}`);
  if (result && write) {
    const spec = file.classes.find((c) => c.id === car.id)!;
    const round = (v: number) => Math.round(v * 1000) / 1000;
    spec.grip = round(result.car.grip);
    spec.clA = [round(result.car.clA[0]), round(result.car.clA[1])];
    spec.loadSensitivity = round(result.car.loadSensitivity);
    spec.calibration = { laps: shown.filter((r) => r.ref.fit).length, rmsError: Math.round(after * 10000) / 10000 };
  }
}

if (write) {
  writeFileSync(`${DATA_DIR}vehicles.json`, formatVehicleFile(file));
  writeFileSync(new URL('../docs/CALIBRATION.md', import.meta.url), calibrationReport());
  console.log('\nWrote data/vehicles.json and docs/CALIBRATION.md');
}

/** Keeps one class per block with its fields on a few lines, like the hand-written file. */
function formatVehicleFile(f: VehicleFile): string {
  const val = (v: unknown) => JSON.stringify(v).replace(/,/g, ', ').replace(/":/g, '": ');
  const classes = f.classes.map((c) => {
    const entries = Object.entries(c);
    const lines: string[] = [];
    const groups = [
      ['id', 'name', 'spec', 'kind', 'color'],
      ['mass', 'powerKw', 'cdA', 'clA'],
      ['grip', 'loadSensitivity', 'driveShare', 'rollingResistance'],
      ['maxAccelG', 'maxBrakeG', 'drs'],
      ['topSpeedKmh', 'gears', 'firstGearKmh'],
      ['calibration'],
    ];
    for (const g of groups) {
      const parts = entries.filter(([k]) => g.includes(k)).map(([k, v]) => `"${k}": ${val(v)}`);
      if (parts.length) lines.push(`      ${parts.join(', ')}`);
    }
    return `    {\n${lines.join(',\n')}\n    }`;
  });
  return `{\n  "version": ${f.version},\n  "notes": ${JSON.stringify(f.notes)},\n  "classes": [\n${classes.join(',\n')}\n  ]\n}\n`;
}

function calibrationReport(): string {
  const all = summary.flatMap((s) => s.rows.filter((r) => r.ref.fit).map((r) => ({ name: s.name, r })));
  const worst = all.reduce((a, b) => (Math.abs(b.r.error) > Math.abs(a.r.error) ? b : a), all[0]);
  const lines = [
    '# Calibration',
    '',
    'Generated by `node scripts/calibrate.ts --write`. The lap-time model runs each class on real circuits from the',
    '[TUMFTM racetrack database](https://github.com/TUMFTM/racetrack-database) (LGPL-3.0) and compares the result with',
    'real qualifying laps from `data/reference-laps.json`.',
    '',
    '## How the classes are set',
    '',
    '- Mass, power and drag come from published figures and are checked against real top speeds (F1 and F2 open DRS on',
    '  straights of 300 m or more, as in qualifying).',
    '- Grip is fitted per class; downforce too for classes with at least three reference laps, between 80% and 125%',
    '  of the published estimate; the tyre load sensitivity with at least four.',
    '- The fitted grip is an effective value, higher than a real tyre\'s: it also absorbs what the model leaves out,',
    '  mainly that a minimum-curvature line is a little slower than a real driver\'s line through slow corners. It is',
    '  consistent across classes, so their relative pace holds on new circuits.',
    '',
    '## Limits',
    '',
    `The circuits are flat (the data has no elevation), the racing line keeps ${LINE_MARGIN} m from each edge, and the`,
    'circuit geometry comes from OpenStreetMap, so some corners are sharper or softer than the real ones. Errors per',
    'circuit therefore mix model error with data error, and classes with one or two reference laps are only loosely',
    `pinned down. The largest single miss is ${worst ? `${worst.name} at ${worst.r.ref.circuit}, ${pct(worst.r.error)}` : 'none'}.`,
    '',
    '## Results',
    '',
    '| Class | RMS error | Circuit | Real | Model | Error |',
    '|---|---|---|---|---|---|',
  ];
  for (const s of summary) {
    s.rows.forEach((r, i) => {
      lines.push(`| ${i === 0 ? s.name : ''} | ${i === 0 ? rms(s.after) : ''} | ${r.ref.circuit}${r.ref.fit ? '' : ' (not fitted)'} | ${formatLapTime(r.ref.time)} | ${formatLapTime(r.simulated)} | ${pct(r.error)} |`);
    });
  }
  lines.push('', 'Sources for every reference lap are listed in `data/reference-laps.json`.', '');
  return lines.join('\n');
}
